const express = require('express');
const authController = require('../controller/authController');
const blogController = require('../controller/blogController');
const auth = require('../middlewares/auth');
const commentController = require('../controller/commentController');
const Router = express.Router();
Router.post('/register',authController.register);
Router.get('/test', (req,res) => res.json({msg:'working'}));
Router.post('/login',authController.login);
Router.post('/logout',auth,  authController.logOut);
Router.post('/refresh', authController.refresh);
Router.post('/blog', auth, blogController.create);
Router.get('/blog/all', auth, blogController.getAll);
Router.get('blog/:id', auth, blogController.getById);
Router.put('/blog', auth, blogController.update);
Router.delete('/blog/:id', auth, blogController.delete);
Router.post('/comment', auth, commentController.create);
Router.get('/comment/:id', auth, commentController.getById);
module.exports = Router;